name: Configure check approval
description: Configure check approval
outputs:
  trusted_apps:
    description: List of trusted apps
    value: ${{ steps.param.outputs.trusted_apps }}
  trusted_machine_users:
    description: List of trusted machine users
    value: ${{ steps.param.outputs.trusted_machine_users }}
  untrusted_machine_users:
    description: List of untrusted machine users
    value: ${{ steps.param.outputs.untrusted_machine_users }}
runs:
  using: composite
  steps:
    - id: param
      name: Set parameters
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          require(`${process.env.GITHUB_ACTION_PATH}/main.js`)(context.repo.repo);
